#!/usr/bin/env bash
# run_recomp.sh — XenonRecomp: XEX + TOML + ppc_context.h -> recomp/generated/*.cpp
# Usage: ./tools/run_recomp.sh [default.xex]
set -euo pipefail
XEX="${1:-./default.xex}"
RECOMP_BIN="${XENON_RECOMP:-./thirdparty/XenonRecomp/build/XenonRecomp}"
PPC_CTX="${PPC_CONTEXT:-./recomp/runtime/ppc_context.h}"
TOML="./tools/fh2recomp.toml"
OUTDIR="./recomp/generated"

test -s "${XEX}" || { echo "Missing ${XEX}; run tools/fetch_xex.sh first." >&2; exit 1; }
[[ -f "${TOML}" ]] || { echo "Missing ${TOML}" >&2; exit 1; }
if [[ ! -x "${RECOMP_BIN}" ]]; then
  echo "XenonRecomp not found at ${RECOMP_BIN} (see run_analyse.sh for build steps)." >&2
  exit 1
fi
mkdir -p "${OUTDIR}"
"${RECOMP_BIN}" "${TOML}" "${PPC_CTX}"
# Normalize output into fh2_sources.cmake for the Android CMake build.
{
  echo '# Auto-generated by tools/run_recomp.sh — do not edit.'
  echo 'set(FH2_GENERATED_SOURCES'
  for f in "${OUTDIR}"/ppc_recomp.*.cpp "${OUTDIR}"/ppc_func_mapping.cpp; do
    [[ -f "$f" ]] && echo "    \"$f\""
  done
  echo ')'
} > "${OUTDIR}/fh2_sources.cmake"
echo "Recompilation finished. Unimplemented-instruction warnings are backlog (docs/backlog.md)."
